#!/usr/bin/env node
'use strict';

var path = require('path');
var spawn = require('@ryanburnette/spawn-in-parallel');

var projectDir = path.resolve(__dirname, '../../..');

spawn([
  {
    cmd: `themes/eon/scripts/hugo-development`,
    opts: {
      cwd: projectDir
    }
  },
  {
    cmd: 'themes/eon/scripts/assets-watch',
    opts: {
      cwd: projectDir
    }
  }
]);
