#!/usr/bin/env node
'use strict';

var path = require('path');
var spawn = require('@ryanburnette/spawn-in-parallel');

var projectDir = path.resolve(__dirname, '../../..');
var cacheDir = path.join(projectDir, '.hugo');

spawn([
  {
    cmd: `hugo server -D -p 3000 --cacheDir ${cacheDir}`,
    opts: {
      cwd: projectDir
    }
  },
  {
    cmd: 'themes/eon/scripts/assets-watch',
    opts: {
      cwd: projectDir
    }
  }
]);
