#!/usr/bin/env node
'use strict';

var path = require('path');
var { spawn } = require('child_process');

var publicDir = path.resolve(__dirname, '../../../public');
var cmd = `npx hash-assets ${publicDir}`;

spawn(cmd, {
  env: {
    PATH: process.env.PATH
  },
  shell: true,
  stdio: ['inherit', 'inherit', 'inherit'],
  cwd: path.resolve(__dirname, '..')
});
