#!/usr/bin/env node
'use strict';

var path = require('path');
var { spawn } = require('child_process');

var projectDir = path.resolve(__dirname, '../../..');

var cmd = 'hugo';

spawn(cmd, {
  env: {
    PATH: process.env.PATH
  },
  shell: true,
  stdio: ['inherit', 'inherit', 'inherit'],
  cwd: projectDir
});
